<?php

header('Access-Control-Allow-Origin=> *');
defined('BASEPATH') OR exit('No direct script access allowed');

class TwitterSearch extends CI_Controller {

	function __construct(){
			parent::__construct();
	}

 public function index(){
				$people = array(
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Fri Aug 10 15:38:27 +0000 2012",
					    "default_profile"=>true,
					    "default_profile_image"=>false,
					    "description"=>"ig =>febianazulhaida",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>11,
					    "follow_request_sent"=>false,
					    "followers_count"=>132,
					    "following"=>false,
					    "friends_count"=>49,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>749563476,
					    "id_str"=>"749563476",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>0,
					    "location"=>"",
					    "name"=>"Febi",
					    "notifications"=>false,
					    "profile_background_color"=>"C0DEED",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/749563476/1424587406",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/569386972578197504/2Vjs2HB4_normal.jpeg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/569386972578197504/2Vjs2HB4_normal.jpeg",
					    "profile_link_color"=>"1DA1F2",
					    "profile_sidebar_border_color"=>"C0DEED",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"FebianaZulhaida",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Sat Oct 29 18:27:54 +0000 2016",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[
					          [
					            "id"=>294996035,
					            "id_str"=>"294996035",
					            "indices"=>[
					              3,
					              18
					            ],
					            "name"=>"AlvaroMaldini",
					            "screen_name"=>"AlvaroMaldini1"
					          ]
					        ]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>792432789450657792,
					      "id_str"=>"792432789450657792",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "retweet_count"=>1999,
					      "retweeted"=>false,
					      "retweeted_status"=>[
					        "contributors"=>null,
					        "coordinates"=>null,
					        "created_at"=>"Mon Oct 24 16:12:09 +0000 2016",
					        "entities"=>[
					          "hashtags"=>[],
					          "symbols"=>[],
					          "urls"=>[],
					          "user_mentions"=>[]
					        ],
					        "favorite_count"=>1278,
					        "favorited"=>false,
					        "geo"=>null,
					        "id"=>790586686950354944,
					        "id_str"=>"790586686950354944",
					        "in_reply_to_screen_name"=>null,
					        "in_reply_to_status_id"=>null,
					        "in_reply_to_status_id_str"=>null,
					        "in_reply_to_user_id"=>null,
					        "in_reply_to_user_id_str"=>null,
					        "is_quote_status"=>false,
					        "lang"=>"in",
					        "place"=>null,
					        "retweet_count"=>1999,
					        "retweeted"=>false,
					        "source"=>"
					<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
					        "text"=>"Saya bukan seperti anak muda sekarang, yang harus punya pacar supaya ada penyemangat",
					        "truncated"=>false
					      ],
					      "source"=>"
					<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
					      "text"=>"RT @AlvaroMaldini1=>Saya bukan seperti anak muda sekarang, yang harus punya pacar supaya ada penyemangat",
					      "truncated"=>false
					    ],
					    "statuses_count"=>1094,
					    "time_zone"=>null,
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>null,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Fri Nov 07 07:35:31 +0000 2014",
					    "default_profile"=>true,
					    "default_profile_image"=>false,
					    "description"=>"",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>92,
					    "follow_request_sent"=>false,
					    "followers_count"=>107,
					    "following"=>false,
					    "friends_count"=>120,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>false,
					    "id"=>2892587143,
					    "id_str"=>"2892587143",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"id",
					    "listed_count"=>0,
					    "location"=>"inkopad city",
					    "name"=>"febira",
					    "notifications"=>false,
					    "profile_background_color"=>"C0DEED",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/2892587143/1466436348",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/726774241324990464/G3uPG7jQ_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/726774241324990464/G3uPG7jQ_normal.jpg",
					    "profile_link_color"=>"1DA1F2",
					    "profile_sidebar_border_color"=>"C0DEED",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>true,
					    "screen_name"=>"febi_rahmaa",
					    "statuses_count"=>2055,
					    "time_zone"=>null,
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>null,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Fri Apr 08 15:34:02 +0000 2016",
					    "default_profile"=>true,
					    "default_profile_image"=>false,
					    "description"=>"ff",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>358,
					    "follow_request_sent"=>false,
					    "followers_count"=>390,
					    "following"=>false,
					    "friends_count"=>1051,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>true,
					    "id"=>718461909561782272,
					    "id_str"=>"718461909561782272",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"id",
					    "listed_count"=>0,
					    "location"=>"Kota Medan, Sumatera Utara",
					    "name"=>"Febi Febiandra",
					    "notifications"=>false,
					    "profile_background_color"=>"F5F8FA",
					    "profile_background_image_url"=>null,
					    "profile_background_image_url_https"=>null,
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/718461909561782272/1460130199",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/784967522822959109/3Y2AVJB3_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/784967522822959109/3Y2AVJB3_normal.jpg",
					    "profile_link_color"=>"1DA1F2",
					    "profile_sidebar_border_color"=>"C0DEED",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"FebiFebiandra",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Thu Mar 09 16:58:02 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"liveplaylist.net/playsnow/html5\u2026",
					            "expanded_url"=>"http://liveplaylist.net/playsnow/html5.php?pf=tw&vid=ytbXT9TP_Ll7Ds&cat=0&img=https%3A%2F%2Fi.ytimg.com%2Fvi%2FXT9TP_Ll7Ds%2Fhqdefault.jpg&t=Sulastomo%20Anak%20IZZI%20di%20Perkosa&dur=300vers%3D4",
					            "indices"=>[
					              40,
					              63
					            ],
					            "url"=>"https://t.co/JfUvDArYvK"
					          ]
					        ],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>839882984807354369,
					      "id_str"=>"839882984807354369",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "possibly_sensitive"=>false,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://liveplaylist.net\" rel=\"nofollow\">Plays Now</a>",
					      "text"=>"plays \"Sulastomo Anak IZZI di Perkosa\"  https://t.co/JfUvDArYvK",
					      "truncated"=>false
					    ],
					    "statuses_count"=>728,
					    "time_zone"=>null,
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>null,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Thu Oct 16 02:14:51 +0000 2014",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"ALLAH | mamah",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>40,
					    "follow_request_sent"=>false,
					    "followers_count"=>65,
					    "following"=>false,
					    "friends_count"=>192,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>true,
					    "id"=>2857542937,
					    "id_str"=>"2857542937",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"id",
					    "listed_count"=>1,
					    "location"=>"",
					    "name"=>"Febi",
					    "notifications"=>false,
					    "profile_background_color"=>"3B94D9",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/545023720566169600/6nafcJVj.png",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/545023720566169600/6nafcJVj.png",
					    "profile_background_tile"=>true,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/2857542937/1460970178",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/786146379219345408/Aq0LFsIx_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/786146379219345408/Aq0LFsIx_normal.jpg",
					    "profile_link_color"=>"DD2E44",
					    "profile_sidebar_border_color"=>"FFFFFF",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>true,
					    "screen_name"=>"febibiii",
					    "statuses_count"=>3051,
					    "time_zone"=>"Jakarta",
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Sat Mar 28 02:07:38 +0000 2015",
					    "default_profile"=>true,
					    "default_profile_image"=>false,
					    "description"=>"need or want",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>202,
					    "follow_request_sent"=>false,
					    "followers_count"=>5226,
					    "following"=>false,
					    "friends_count"=>59,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>false,
					    "id"=>3111985417,
					    "id_str"=>"3111985417",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"id",
					    "listed_count"=>6,
					    "location"=>"",
					    "name"=>"Lita Febi",
					    "notifications"=>false,
					    "profile_background_color"=>"C0DEED",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/3111985417/1477529810",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/708539757878317057/_eLA63ru_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/708539757878317057/_eLA63ru_normal.jpg",
					    "profile_link_color"=>"1DA1F2",
					    "profile_sidebar_border_color"=>"C0DEED",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"litafebi",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Mon May 08 07:08:04 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>6,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>861477788749975552,
					      "id_str"=>"861477788749975552",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "retweet_count"=>3,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
					      "text"=>"Senin sibuk, gak ada yang bisa diajak jalan \ud83d\udd58\ud83d\udd59\ud83d\udd5a\ud83d\udd5b\ud83d\udd5c\ud83d\udd5d\ud83d\udd5e\ud83d\udd5f\ud83d\udd60\ud83d\udd61\ud83d\udd62\ud83d\udd63\ud83d\udd63\ud83d\udd64",
					      "truncated"=>false
					    ],
					    "statuses_count"=>3622,
					    "time_zone"=>null,
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>null,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Fri Mar 09 09:44:55 +0000 2012",
					    "default_profile"=>true,
					    "default_profile_image"=>false,
					    "description"=>"saksikan blink setiap hari di sctv",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>0,
					    "follow_request_sent"=>false,
					    "followers_count"=>7011,
					    "following"=>false,
					    "friends_count"=>25,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>519346386,
					    "id_str"=>"519346386",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>2,
					    "location"=>"",
					    "name"=>"feby blink",
					    "notifications"=>false,
					    "profile_background_color"=>"C0DEED",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_tile"=>false,
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/1883407664/blink-yang-nge-blink-putih-abu-abu-17700_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/1883407664/blink-yang-nge-blink-putih-abu-abu-17700_normal.jpg",
					    "profile_link_color"=>"1DA1F2",
					    "profile_sidebar_border_color"=>"C0DEED",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"febi_blink",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Fri Mar 09 09:47:33 +0000 2012",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>47,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>178054408632942592,
					      "id_str"=>"178054408632942592",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "retweet_count"=>41,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
					      "text"=>"selamat soreee nonton blink yah nanti",
					      "truncated"=>false
					    ],
					    "statuses_count"=>1,
					    "time_zone"=>null,
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>null,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Thu Nov 26 06:13:42 +0000 2009",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"Eastern MCMXCI",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ],
					      "url"=>[
					        "urls"=>[
					          [
					            "display_url"=>"youtube.com/fadilahfebi",
					            "expanded_url"=>"http://youtube.com/fadilahfebi",
					            "indices"=>[
					              0,
					              22
					            ],
					            "url"=>"http://t.co/T3rPrcYXTB"
					          ]
					        ]
					      ]
					    ],
					    "favourites_count"=>1,
					    "follow_request_sent"=>false,
					    "followers_count"=>2247,
					    "following"=>false,
					    "friends_count"=>284,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>false,
					    "id"=>92697419,
					    "id_str"=>"92697419",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>28,
					    "location"=>"",
					    "name"=>"Fadil Febi",
					    "notifications"=>false,
					    "profile_background_color"=>"131516",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/83035345/akoko.jpg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/83035345/akoko.jpg",
					    "profile_background_tile"=>true,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/92697419/1423397450",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/588592594537422848/s-IMlJfp_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/588592594537422848/s-IMlJfp_normal.jpg",
					    "profile_link_color"=>"979FDE",
					    "profile_sidebar_border_color"=>"050505",
					    "profile_sidebar_fill_color"=>"023354",
					    "profile_text_color"=>"4EA8CC",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"fadilfebi",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Tue May 03 16:43:11 +0000 2016",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"youtube.com/watch?v=KxXnsz\u2026",
					            "expanded_url"=>"https://www.youtube.com/watch?v=KxXnszCqpZo&feature=share",
					            "indices"=>[
					              32,
					              55
					            ],
					            "url"=>"https://t.co/xcpSRz1Xt2"
					          ]
					        ],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>727539009178636288,
					      "id_str"=>"727539009178636288",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"und",
					      "place"=>null,
					      "possibly_sensitive"=>false,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
					      "text"=>"VLOG 1 FADILFEBI - JEMPUT PACAR https://t.co/xcpSRz1Xt2",
					      "truncated"=>false
					    ],
					    "statuses_count"=>14077,
					    "time_zone"=>"Jakarta",
					    "translator_type"=>"none",
					    "url"=>"http://t.co/T3rPrcYXTB",
					    "utc_offset"=>25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Fri Oct 19 14:18:12 +0000 2012",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"model ll ig =>arini_manis",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>256,
					    "follow_request_sent"=>false,
					    "followers_count"=>16228,
					    "following"=>false,
					    "friends_count"=>8738,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>true,
					    "id"=>891073153,
					    "id_str"=>"891073153",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>1,
					    "location"=>"cilacap jawa tengah",
					    "name"=>"febi dwi bestari",
					    "notifications"=>false,
					    "profile_background_color"=>"8A2D7F",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/378800000073868282/1ccef50ddf8b3904278dcc2ec8e3ddc1.jpeg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/378800000073868282/1ccef50ddf8b3904278dcc2ec8e3ddc1.jpeg",
					    "profile_background_tile"=>true,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/891073153/1428495117",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/815277977181134848/afV-Cn7f_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/815277977181134848/afV-Cn7f_normal.jpg",
					    "profile_link_color"=>"9266CC",
					    "profile_sidebar_border_color"=>"FFFFFF",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"arini_yms",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Sat Dec 31 19:38:02 +0000 2016",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[
					          [
					            "id"=>458487990,
					            "id_str"=>"458487990",
					            "indices"=>[
					              20,
					              32
					            ],
					            "name"=>"arini manis",
					            "screen_name"=>"arini_manis"
					          ]
					        ]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>815280874799255552,
					      "id_str"=>"815280874799255552",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"en",
					      "place"=>null,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
					      "text"=>"Follow My Instagram @arini_manis",
					      "truncated"=>false
					    ],
					    "statuses_count"=>12562,
					    "time_zone"=>"Jakarta",
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Fri Oct 30 08:46:55 +0000 2009",
					    "default_profile"=>true,
					    "default_profile_image"=>false,
					    "description"=>"",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>1,
					    "follow_request_sent"=>false,
					    "followers_count"=>62,
					    "following"=>false,
					    "friends_count"=>39,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>86270030,
					    "id_str"=>"86270030",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>0,
					    "location"=>"Bali",
					    "name"=>"Febriyani",
					    "notifications"=>false,
					    "profile_background_color"=>"C0DEED",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_tile"=>false,
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/378800000476901727/fc8d19e5c35828d981705cb919348db5_normal.jpeg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/378800000476901727/fc8d19e5c35828d981705cb919348db5_normal.jpeg",
					    "profile_link_color"=>"1DA1F2",
					    "profile_sidebar_border_color"=>"C0DEED",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"DewiFebi",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Sat May 06 08:20:39 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"path.com/p/3NkF7T",
					            "expanded_url"=>"https://path.com/p/3NkF7T",
					            "indices"=>[
					              34,
					              57
					            ],
					            "url"=>"https://t.co/PSo9VclE2I"
					          ]
					        ],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>860771278134796288,
					      "id_str"=>"860771278134796288",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"en",
					      "place"=>null,
					      "possibly_sensitive"=>false,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"https://path.com/\" rel=\"nofollow\">Path</a>",
					      "text"=>"With Icha, Dewi, and BuDa [pic] \u2014 https://t.co/PSo9VclE2I",
					      "truncated"=>false
					    ],
					    "statuses_count"=>1556,
					    "time_zone"=>null,
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>null,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Mon May 13 10:18:59 +0000 2013",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"Seberapa jauh kamu berhasil dalam hidup tergantung pada kelembutanmu pada yang muda, kasih sayangmu pada yang tua, rasa simpatimu pada perjuangan.",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ],
					      "url"=>[
					        "urls"=>[
					          [
					            "display_url"=>"febstark.blogspot.com",
					            "expanded_url"=>"http://febstark.blogspot.com",
					            "indices"=>[
					              0,
					              22
					            ],
					            "url"=>"http://t.co/ytYLB32rMq"
					          ]
					        ]
					      ]
					    ],
					    "favourites_count"=>35,
					    "follow_request_sent"=>false,
					    "followers_count"=>229,
					    "following"=>false,
					    "friends_count"=>1093,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>true,
					    "id"=>1425171968,
					    "id_str"=>"1425171968",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"id",
					    "listed_count"=>0,
					    "location"=>"Tasikmalaya Indonesia",
					    "name"=>"Febi Ramdani",
					    "notifications"=>false,
					    "profile_background_color"=>"000000",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/1425171968/1458537179",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/711782644187443200/DOi9_xjy_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/711782644187443200/DOi9_xjy_normal.jpg",
					    "profile_link_color"=>"0084B4",
					    "profile_sidebar_border_color"=>"000000",
					    "profile_sidebar_fill_color"=>"000000",
					    "profile_text_color"=>"000000",
					    "profile_use_background_image"=>false,
					    "protected"=>false,
					    "screen_name"=>"Feb_Stark24",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Thu Mar 24 14:06:16 +0000 2016",
					      "entities"=>[
					        "hashtags"=>[
					          [
					            "indices"=>[
					              11,
					              28
					            ],
					            "text"=>"NationalPuppyDay"
					          ]
					        ],
					        "media"=>[
					          [
					            "display_url"=>"pic.twitter.com/MN1OqrmK86",
					            "expanded_url"=>"https://twitter.com/Feb_Stark24/status/713004004536508416/photo/1",
					            "id"=>713003980993863681,
					            "id_str"=>"713003980993863681",
					            "indices"=>[
					              29,
					              52
					            ],
					            "media_url"=>"http://pbs.twimg.com/media/CeUZV9KUIAEhfNH.jpg",
					            "media_url_https"=>"https://pbs.twimg.com/media/CeUZV9KUIAEhfNH.jpg",
					            "sizes"=>[
					              "large"=>[
					                "h"=>480,
					                "resize"=>"fit",
					                "w"=>854
					              ],
					              "medium"=>[
					                "h"=>337,
					                "resize"=>"fit",
					                "w"=>600
					              ],
					              "small"=>[
					                "h"=>191,
					                "resize"=>"fit",
					                "w"=>340
					              ],
					              "thumb"=>[
					                "h"=>150,
					                "resize"=>"crop",
					                "w"=>150
					              ]
					            ],
					            "type"=>"photo",
					            "url"=>"https://t.co/MN1OqrmK86"
					          ]
					        ],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[
					          [
					            "id"=>43081642,
					            "id_str"=>"43081642",
					            "indices"=>[
					              0,
					              10
					            ],
					            "name"=>"Pevita Pearce \u262e",
					            "screen_name"=>"pevpearce"
					          ]
					        ]
					      ],
					      "extended_entities"=>[
					        "media"=>[
					          [
					            "display_url"=>"pic.twitter.com/MN1OqrmK86",
					            "expanded_url"=>"https://twitter.com/Feb_Stark24/status/713004004536508416/photo/1",
					            "id"=>713003980993863681,
					            "id_str"=>"713003980993863681",
					            "indices"=>[
					              29,
					              52
					            ],
					            "media_url"=>"http://pbs.twimg.com/media/CeUZV9KUIAEhfNH.jpg",
					            "media_url_https"=>"https://pbs.twimg.com/media/CeUZV9KUIAEhfNH.jpg",
					            "sizes"=>[
					              "large"=>[
					                "h"=>480,
					                "resize"=>"fit",
					                "w"=>854
					              ],
					              "medium"=>[
					                "h"=>337,
					                "resize"=>"fit",
					                "w"=>600
					              ],
					              "small"=>[
					                "h"=>191,
					                "resize"=>"fit",
					                "w"=>340
					              ],
					              "thumb"=>[
					                "h"=>150,
					                "resize"=>"crop",
					                "w"=>150
					              ]
					            ],
					            "type"=>"photo",
					            "url"=>"https://t.co/MN1OqrmK86"
					          ]
					        ]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>713004004536508416,
					      "id_str"=>"713004004536508416",
					      "in_reply_to_screen_name"=>"pevpearce",
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>43081642,
					      "in_reply_to_user_id_str"=>"43081642",
					      "is_quote_status"=>false,
					      "lang"=>"und",
					      "place"=>[
					        "attributes"=>[],
					        "bounding_box"=>[
					          "coordinates"=>[
					            [
					              [
					                108.072879,
					                -7.211295
					              ],
					              [
					                108.171951,
					                -7.211295
					              ],
					              [
					                108.171951,
					                -7.088319
					              ],
					              [
					                108.072879,
					                -7.088319
					              ]
					            ]
					          ],
					          "type"=>"Polygon"
					        ],
					        "contained_within"=>[],
					        "country"=>"Indonesia",
					        "country_code"=>"ID",
					        "full_name"=>"Ciawi, Indonesia",
					        "id"=>"931d476c6924e9fd",
					        "name"=>"Ciawi",
					        "place_type"=>"city",
					        "url"=>"https://api.twitter.com/1.1/geo/id/931d476c6924e9fd.json"
					      ],
					      "possibly_sensitive"=>true,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
					      "text"=>"@pevpearce #NationalPuppyDay https://t.co/MN1OqrmK86",
					      "truncated"=>false
					    ],
					    "statuses_count"=>222,
					    "time_zone"=>"Jakarta",
					    "translator_type"=>"none",
					    "url"=>"http://t.co/ytYLB32rMq",
					    "utc_offset"=>25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Mon Feb 08 07:01:31 +0000 2010",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"(18-02-1992) Nothing can you do, before you try.\nSubscirbe my youtube channel\nSei Madarama",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ],
					      "url"=>[
					        "urls"=>[
					          [
					            "display_url"=>"youtube.com/channel/UCxi_J\u2026",
					            "expanded_url"=>"https://www.youtube.com/channel/UCxi_Jev5R7F7ik763Z3oyFA?sub_confirmation=1",
					            "indices"=>[
					              0,
					              23
					            ],
					            "url"=>"https://t.co/01B4yQrku2"
					          ]
					        ]
					      ]
					    ],
					    "favourites_count"=>75,
					    "follow_request_sent"=>false,
					    "followers_count"=>70,
					    "following"=>false,
					    "friends_count"=>65,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>true,
					    "id"=>112366918,
					    "id_str"=>"112366918",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"id",
					    "listed_count"=>3,
					    "location"=>"Pharmindo,Cimahi-Indonesia.",
					    "name"=>"Febi Sukma Pramadita",
					    "notifications"=>false,
					    "profile_background_color"=>"143211",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/435689959891017728/P5rBWksn.jpeg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/435689959891017728/P5rBWksn.jpeg",
					    "profile_background_tile"=>true,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/112366918/1476153268",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/785670109964623872/a5SFR4A7_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/785670109964623872/a5SFR4A7_normal.jpg",
					    "profile_link_color"=>"19CF86",
					    "profile_sidebar_border_color"=>"000000",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"Eld_Conire",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Mon May 08 11:35:13 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"instagram.com/p/BT1HLQ6ABm1L\u2026",
					            "expanded_url"=>"https://www.instagram.com/p/BT1HLQ6ABm1L1RJ09ZZZuAr7Y25uScPaoD_CW80/",
					            "indices"=>[
					              25,
					              48
					            ],
					            "url"=>"https://t.co/SjYF7ltUCm"
					          ]
					        ],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>861545015767699456,
					      "id_str"=>"861545015767699456",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "possibly_sensitive"=>true,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://instagram.com\" rel=\"nofollow\">Instagram</a>",
					      "text"=>"Perubahannya tidak buruk https://t.co/SjYF7ltUCm",
					      "truncated"=>false
					    ],
					    "statuses_count"=>1578,
					    "time_zone"=>"Jakarta",
					    "translator_type"=>"none",
					    "url"=>"https://t.co/01B4yQrku2",
					    "utc_offset"=>25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Wed Oct 13 03:29:45 +0000 2010",
					    "default_profile"=>true,
					    "default_profile_image"=>false,
					    "description"=>"Islamic Financial Advisor & Educator / Writer / Online Class Tutor at http://t.co/0kKeAfYu9f / #IngatMati / CP =>management@fabfebi.com",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[
					          [
					            "display_url"=>"medidu.com",
					            "expanded_url"=>"http://www.medidu.com",
					            "indices"=>[
					              70,
					              92
					            ],
					            "url"=>"http://t.co/0kKeAfYu9f"
					          ]
					        ]
					      ],
					      "url"=>[
					        "urls"=>[
					          [
					            "display_url"=>"fabfebi.com",
					            "expanded_url"=>"http://www.fabfebi.com/",
					            "indices"=>[
					              0,
					              22
					            ],
					            "url"=>"http://t.co/LJvqVnWPGP"
					          ]
					        ]
					      ]
					    ],
					    "favourites_count"=>72,
					    "follow_request_sent"=>false,
					    "followers_count"=>8082,
					    "following"=>false,
					    "friends_count"=>3425,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>202016159,
					    "id_str"=>"202016159",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>39,
					    "location"=>"Bandung, Jakarta",
					    "name"=>"Febiola Aryanti",
					    "notifications"=>false,
					    "profile_background_color"=>"C0DEED",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme1/bg.png",
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/202016159/1446780008",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/662455796714700800/ZVB4BlF3_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/662455796714700800/ZVB4BlF3_normal.jpg",
					    "profile_link_color"=>"1DA1F2",
					    "profile_sidebar_border_color"=>"C0DEED",
					    "profile_sidebar_fill_color"=>"DDEEF6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"FabFebi",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Thu Mar 30 14:24:17 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[
					          [
					            "indices"=>[
					              63,
					              69
					            ],
					            "text"=>"arrow"
					          ],
					          [
					            "indices"=>[
					              70,
					              74
					            ],
					            "text"=>"bow"
					          ],
					          [
					            "indices"=>[
					              75,
					              83
					            ],
					            "text"=>"archery"
					          ],
					          [
					            "indices"=>[
					              84,
					              91
					            ],
					            "text"=>"archer"
					          ]
					        ],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"instagram.com/p/BSQ_hNYh_vV/",
					            "expanded_url"=>"https://www.instagram.com/p/BSQ_hNYh_vV/",
					            "indices"=>[
					              93,
					              116
					            ],
					            "url"=>"https://t.co/APEk4dBNpI"
					          ]
					        ],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>1,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>847454437463306240,
					      "id_str"=>"847454437463306240",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"en",
					      "place"=>null,
					      "possibly_sensitive"=>false,
					      "retweet_count"=>1,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://instagram.com\" rel=\"nofollow\">Instagram</a>",
					      "text"=>"\"Truth is the best arrow and courage finest bow\" - Eva Ritchey\n#arrow #bow #archery #archer\u2026 https://t.co/APEk4dBNpI",
					      "truncated"=>false
					    ],
					    "statuses_count"=>14885,
					    "time_zone"=>"Pacific Time (US & Canada)",
					    "translator_type"=>"none",
					    "url"=>"http://t.co/LJvqVnWPGP",
					    "utc_offset"=>-25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Mon Feb 22 03:19:57 +0000 2010",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"Sorority princess",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>0,
					    "follow_request_sent"=>false,
					    "followers_count"=>31,
					    "following"=>false,
					    "friends_count"=>35,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>116339993,
					    "id_str"=>"116339993",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>2,
					    "location"=>"",
					    "name"=>"Febi",
					    "notifications"=>false,
					    "profile_background_color"=>"B2DFDA",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme13/bg.gif",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme13/bg.gif",
					    "profile_background_tile"=>false,
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/2334668963/utdicuffdcnq5jefkdqu_normal.jpeg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/2334668963/utdicuffdcnq5jefkdqu_normal.jpeg",
					    "profile_link_color"=>"93A644",
					    "profile_sidebar_border_color"=>"EEEEEE",
					    "profile_sidebar_fill_color"=>"FFFFFF",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>true,
					    "screen_name"=>"suchspringtime",
					    "statuses_count"=>1732,
					    "time_zone"=>"Pacific Time (US & Canada)",
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>-25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Fri Jan 01 12:53:54 +0000 2010",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"A Bibliophile",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>574,
					    "follow_request_sent"=>false,
					    "followers_count"=>762,
					    "following"=>false,
					    "friends_count"=>431,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>false,
					    "id"=>100969844,
					    "id_str"=>"100969844",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>7,
					    "location"=>"D 202 FL",
					    "name"=>"R.A Febi Laraswati",
					    "notifications"=>false,
					    "profile_background_color"=>"EDECE9",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/90475772/ss2008papgapde3nu1ne0.jpg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/90475772/ss2008papgapde3nu1ne0.jpg",
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/100969844/1368618939",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/378800000269172423/78ebd3645b6dffabd8899c890c27925c_normal.png",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/378800000269172423/78ebd3645b6dffabd8899c890c27925c_normal.png",
					    "profile_link_color"=>"088253",
					    "profile_sidebar_border_color"=>"D3D2CF",
					    "profile_sidebar_fill_color"=>"E3E2DE",
					    "profile_text_color"=>"634047",
					    "profile_use_background_image"=>true,
					    "protected"=>true,
					    "screen_name"=>"radenfeby",
					    "statuses_count"=>27142,
					    "time_zone"=>"Jakarta",
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Wed May 13 01:31:45 +0000 2009",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"Dallas",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ],
					      "url"=>[
					        "urls"=>[
					          [
					            "display_url"=>"instagram.com/anisasafrinda",
					            "expanded_url"=>"http://instagram.com/anisasafrinda",
					            "indices"=>[
					              0,
					              22
					            ],
					            "url"=>"http://t.co/rHKWnZvAu9"
					          ]
					        ]
					      ]
					    ],
					    "favourites_count"=>33,
					    "follow_request_sent"=>false,
					    "followers_count"=>696,
					    "following"=>false,
					    "friends_count"=>286,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>39654255,
					    "id_str"=>"39654255",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>6,
					    "location"=>"Depth of despair",
					    "name"=>"A. Febi Safrinda",
					    "notifications"=>false,
					    "profile_background_color"=>"131516",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/266668559/annasui-charmbracelet.jpg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/266668559/annasui-charmbracelet.jpg",
					    "profile_background_tile"=>true,
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/378800000783410611/c505a8d4f2f0afa2adf4bc23f2c32ece_normal.jpeg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/378800000783410611/c505a8d4f2f0afa2adf4bc23f2c32ece_normal.jpeg",
					    "profile_link_color"=>"009999",
					    "profile_sidebar_border_color"=>"EEEEEE",
					    "profile_sidebar_fill_color"=>"EFEFEF",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"anisasafrinda",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Tue Sep 20 13:55:48 +0000 2016",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[
					          [
					            "id"=>89335172,
					            "id_str"=>"89335172",
					            "indices"=>[
					              0,
					              16
					            ],
					            "name"=>"Fidella Anandhita S",
					            "screen_name"=>"fidellanandhita"
					          ]
					        ]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>778231188808798210,
					      "id_str"=>"778231188808798210",
					      "in_reply_to_screen_name"=>"fidellanandhita",
					      "in_reply_to_status_id"=>776482645148434432,
					      "in_reply_to_status_id_str"=>"776482645148434432",
					      "in_reply_to_user_id"=>89335172,
					      "in_reply_to_user_id_str"=>"89335172",
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
					      "text"=>"@fidellanandhita kalo boleh tau itu nontonnya dimana yaaa? Saya cari2 ga nemu..",
					      "truncated"=>false
					    ],
					    "statuses_count"=>20452,
					    "time_zone"=>"Paris",
					    "translator_type"=>"none",
					    "url"=>"http://t.co/rHKWnZvAu9",
					    "utc_offset"=>7200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Sun Nov 14 11:29:48 +0000 2010",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"definitely simple person, straight to the point, loves chocolate, ChelseaFC Fans, @hangerpants worker , @astisahir 's Partner.",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>30,
					    "follow_request_sent"=>false,
					    "followers_count"=>519,
					    "following"=>false,
					    "friends_count"=>717,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>215595014,
					    "id_str"=>"215595014",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>3,
					    "location"=>"\u00dcT=>-6.3789639,106.8556772",
					    "name"=>"Fortuna Febi Fajri",
					    "notifications"=>false,
					    "profile_background_color"=>"4D575C",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/378800000169584129/G8IZybd5.jpeg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/378800000169584129/G8IZybd5.jpeg",
					    "profile_background_tile"=>true,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/215595014/1462424187",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/860080085616869376/_IvYpUfa_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/860080085616869376/_IvYpUfa_normal.jpg",
					    "profile_link_color"=>"0B00A8",
					    "profile_sidebar_border_color"=>"000000",
					    "profile_sidebar_fill_color"=>"000000",
					    "profile_text_color"=>"465780",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"fortunafebii",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Tue May 09 09:27:05 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[
					          [
					            "id"=>115286138,
					            "id_str"=>"115286138",
					            "indices"=>[
					              16,
					              27
					            ],
					            "name"=>"Ahok Basuki TPurnama",
					            "screen_name"=>"basuki_btp"
					          ]
					        ]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>861875159380054016,
					      "id_str"=>"861875159380054016",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "retweet_count"=>1,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
					      "text"=>"Terimakasih pak @basuki_btp Jakarta banyak berubah menjadi lebih baik karena Bapak !",
					      "truncated"=>false
					    ],
					    "statuses_count"=>22843,
					    "time_zone"=>null,
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>null,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Mon Jul 25 15:16:47 +0000 2011",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"The more we are grateful, the more happiness\nwe get.\u25a1\u25a1\u25a1 Ig:febiifebrinaa \u25a0",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ],
					      "url"=>[
					        "urls"=>[
					          [
					            "display_url"=>"anastasia-official.blogspot.com",
					            "expanded_url"=>"http://anastasia-official.blogspot.com",
					            "indices"=>[
					              0,
					              22
					            ],
					            "url"=>"http://t.co/Nh4vJWThDe"
					          ]
					        ]
					      ]
					    ],
					    "favourites_count"=>727,
					    "follow_request_sent"=>false,
					    "followers_count"=>1476,
					    "following"=>false,
					    "friends_count"=>1095,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>false,
					    "id"=>342143946,
					    "id_str"=>"342143946",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>1,
					    "location"=>"",
					    "name"=>"Anastasia Febrina",
					    "notifications"=>false,
					    "profile_background_color"=>"3D2C3D",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/378800000173201263/NyySNGxk.jpeg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/378800000173201263/NyySNGxk.jpeg",
					    "profile_background_tile"=>true,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/342143946/1444616830",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/653396480581984256/4rzqzVBb_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/653396480581984256/4rzqzVBb_normal.jpg",
					    "profile_link_color"=>"F33073",
					    "profile_sidebar_border_color"=>"FFFFFF",
					    "profile_sidebar_fill_color"=>"9AF5E3",
					    "profile_text_color"=>"000000",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"febi_febrina",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Sun May 07 08:08:08 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"fllwrs.com",
					            "expanded_url"=>"http://fllwrs.com",
					            "indices"=>[
					              49,
					              72
					            ],
					            "url"=>"https://t.co/uECjUSPqSZ"
					          ]
					        ],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>861130514325016576,
					      "id_str"=>"861130514325016576",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"en",
					      "place"=>null,
					      "possibly_sensitive"=>false,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://fllwrs.com\" rel=\"nofollow\">fllwrs</a>",
					      "text"=>"4 people followed me // automatically checked by https://t.co/uECjUSPqSZ",
					      "truncated"=>false
					    ],
					    "statuses_count"=>63176,
					    "time_zone"=>"Pacific Time (US & Canada)",
					    "translator_type"=>"none",
					    "url"=>"http://t.co/Nh4vJWThDe",
					    "utc_offset"=>-25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Wed Nov 17 11:56:21 +0000 2010",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"HilmanAnfasa",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>16,
					    "follow_request_sent"=>false,
					    "followers_count"=>791,
					    "following"=>false,
					    "friends_count"=>403,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>216666429,
					    "id_str"=>"216666429",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>0,
					    "location"=>"@CloWildcats",
					    "name"=>"febi",
					    "notifications"=>false,
					    "profile_background_color"=>"ACDED6",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme18/bg.gif",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme18/bg.gif",
					    "profile_background_tile"=>false,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/216666429/1385982279",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/549414195578417153/FJj6STgZ_normal.jpeg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/549414195578417153/FJj6STgZ_normal.jpeg",
					    "profile_link_color"=>"038543",
					    "profile_sidebar_border_color"=>"EEEEEE",
					    "profile_sidebar_fill_color"=>"F6F6F6",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"febriantiadi",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Fri Oct 23 11:54:50 +0000 2015",
					      "entities"=>[
					        "hashtags"=>[
					          [
					            "indices"=>[
					              19,
					              33
					            ],
					            "text"=>"INVALESCO2015"
					          ]
					        ],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"bit.ly/1WP1Q3k",
					            "expanded_url"=>"http://bit.ly/1WP1Q3k",
					            "indices"=>[
					              103,
					              126
					            ],
					            "url"=>"https://t.co/eeuO51dkUV"
					          ]
					        ],
					        "user_mentions"=>[
					          [
					            "id"=>143634855,
					            "id_str"=>"143634855",
					            "indices"=>[
					              3,
					              17
					            ],
					            "name"=>"Event Surabaya",
					            "screen_name"=>"eventsurabaya"
					          ],
					          [
					            "id"=>68166237,
					            "id_str"=>"68166237",
					            "indices"=>[
					              37,
					              44
					            ],
					            "name"=>"Princess Joana",
					            "screen_name"=>"PJoana"
					          ],
					          [
					            "id"=>82592435,
					            "id_str"=>"82592435",
					            "indices"=>[
					              45,
					              55
					            ],
					            "name"=>"Andra & the BackBone",
					            "screen_name"=>"ABackBone"
					          ],
					          [
					            "id"=>80371421,
					            "id_str"=>"80371421",
					            "indices"=>[
					              56,
					              72
					            ],
					            "name"=>"Marcello Tahitoe",
					            "screen_name"=>"MarcelloTahitoe"
					          ],
					          [
					            "id"=>122027894,
					            "id_str"=>"122027894",
					            "indices"=>[
					              87,
					              102
					            ],
					            "name"=>"TUNJUNGAN PLAZA",
					            "screen_name"=>"TUNJUNGANPLAZA"
					          ]
					        ]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>657525585267195907,
					      "id_str"=>"657525585267195907",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"in",
					      "place"=>null,
					      "possibly_sensitive"=>false,
					      "retweet_count"=>9,
					      "retweeted"=>false,
					      "retweeted_status"=>[
					        "contributors"=>null,
					        "coordinates"=>null,
					        "created_at"=>"Fri Oct 23 09:13:01 +0000 2015",
					        "entities"=>[
					          "hashtags"=>[
					            [
					              "indices"=>[
					                0,
					                14
					              ],
					              "text"=>"INVALESCO2015"
					            ]
					          ],
					          "media"=>[
					            [
					              "display_url"=>"pic.twitter.com/qldpYN1dp7",
					              "expanded_url"=>"https://twitter.com/eventsurabaya/status/657484863579095040/photo/1",
					              "id"=>657484862610280448,
					              "id_str"=>"657484862610280448",
					              "indices"=>[
					                108,
					                131
					              ],
					              "media_url"=>"http://pbs.twimg.com/media/CR_a_8EVEAAk0mJ.jpg",
					              "media_url_https"=>"https://pbs.twimg.com/media/CR_a_8EVEAAk0mJ.jpg",
					              "sizes"=>[
					                "large"=>[
					                  "h"=>707,
					                  "resize"=>"fit",
					                  "w"=>500
					                ],
					                "medium"=>[
					                  "h"=>707,
					                  "resize"=>"fit",
					                  "w"=>500
					                ],
					                "small"=>[
					                  "h"=>481,
					                  "resize"=>"fit",
					                  "w"=>340
					                ],
					                "thumb"=>[
					                  "h"=>150,
					                  "resize"=>"crop",
					                  "w"=>150
					                ]
					              ],
					              "type"=>"photo",
					              "url"=>"https://t.co/qldpYN1dp7"
					            ]
					          ],
					          "symbols"=>[],
					          "urls"=>[
					            [
					              "display_url"=>"bit.ly/1WP1Q3k",
					              "expanded_url"=>"http://bit.ly/1WP1Q3k",
					              "indices"=>[
					                84,
					                107
					              ],
					              "url"=>"https://t.co/eeuO51dkUV"
					            ]
					          ],
					          "user_mentions"=>[
					            [
					              "id"=>68166237,
					              "id_str"=>"68166237",
					              "indices"=>[
					                18,
					                25
					              ],
					              "name"=>"Princess Joana",
					              "screen_name"=>"PJoana"
					            ],
					            [
					              "id"=>82592435,
					              "id_str"=>"82592435",
					              "indices"=>[
					                26,
					                36
					              ],
					              "name"=>"Andra & the BackBone",
					              "screen_name"=>"ABackBone"
					            ],
					            [
					              "id"=>80371421,
					              "id_str"=>"80371421",
					              "indices"=>[
					                37,
					                53
					              ],
					              "name"=>"Marcello Tahitoe",
					              "screen_name"=>"MarcelloTahitoe"
					            ],
					            [
					              "id"=>122027894,
					              "id_str"=>"122027894",
					              "indices"=>[
					                68,
					                83
					              ],
					              "name"=>"TUNJUNGAN PLAZA",
					              "screen_name"=>"TUNJUNGANPLAZA"
					            ]
					          ]
					        ],
					        "extended_entities"=>[
					          "media"=>[
					            [
					              "display_url"=>"pic.twitter.com/qldpYN1dp7",
					              "expanded_url"=>"https://twitter.com/eventsurabaya/status/657484863579095040/photo/1",
					              "id"=>657484862610280448,
					              "id_str"=>"657484862610280448",
					              "indices"=>[
					                108,
					                131
					              ],
					              "media_url"=>"http://pbs.twimg.com/media/CR_a_8EVEAAk0mJ.jpg",
					              "media_url_https"=>"https://pbs.twimg.com/media/CR_a_8EVEAAk0mJ.jpg",
					              "sizes"=>[
					                "large"=>[
					                  "h"=>707,
					                  "resize"=>"fit",
					                  "w"=>500
					                ],
					                "medium"=>[
					                  "h"=>707,
					                  "resize"=>"fit",
					                  "w"=>500
					                ],
					                "small"=>[
					                  "h"=>481,
					                  "resize"=>"fit",
					                  "w"=>340
					                ],
					                "thumb"=>[
					                  "h"=>150,
					                  "resize"=>"crop",
					                  "w"=>150
					                ]
					              ],
					              "type"=>"photo",
					              "url"=>"https://t.co/qldpYN1dp7"
					            ]
					          ]
					        ],
					        "favorite_count"=>0,
					        "favorited"=>false,
					        "geo"=>null,
					        "id"=>657484863579095040,
					        "id_str"=>"657484863579095040",
					        "in_reply_to_screen_name"=>null,
					        "in_reply_to_status_id"=>null,
					        "in_reply_to_status_id_str"=>null,
					        "in_reply_to_user_id"=>null,
					        "in_reply_to_user_id_str"=>null,
					        "is_quote_status"=>false,
					        "lang"=>"in",
					        "place"=>null,
					        "possibly_sensitive"=>false,
					        "retweet_count"=>9,
					        "retweeted"=>false,
					        "source"=>"
					<a href=\"http://sproutsocial.com\" rel=\"nofollow\">Sprout Social</a>",
					        "text"=>"#INVALESCO2015 w/ @PJoana @ABackBone @MarcelloTahitoe | 6 Nov'15 Di @TUNJUNGANPLAZA https://t.co/eeuO51dkUV https://t.co/qldpYN1dp7",
					        "truncated"=>false
					      ],
					      "source"=>"
					<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
					      "text"=>"RT @eventsurabaya=>#INVALESCO2015 w/ @PJoana @ABackBone @MarcelloTahitoe | 6 Nov'15 Di @TUNJUNGANPLAZA https://t.co/eeuO51dkUV https://t.co\u2026",
					      "truncated"=>false
					    ],
					    "statuses_count"=>18739,
					    "time_zone"=>"Pacific Time (US & Canada)",
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>-25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Mon Jul 27 11:47:30 +0000 2009",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"An ex advertising slaved and a happy housewife with two handsome boys...",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ]
					    ],
					    "favourites_count"=>1,
					    "follow_request_sent"=>false,
					    "followers_count"=>503,
					    "following"=>false,
					    "friends_count"=>218,
					    "geo_enabled"=>false,
					    "has_extended_profile"=>false,
					    "id"=>60573170,
					    "id_str"=>"60573170",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>6,
					    "location"=>"just here ",
					    "name"=>"febi fenti",
					    "notifications"=>false,
					    "profile_background_color"=>"EBEBEB",
					    "profile_background_image_url"=>"http://abs.twimg.com/images/themes/theme7/bg.gif",
					    "profile_background_image_url_https"=>"https://abs.twimg.com/images/themes/theme7/bg.gif",
					    "profile_background_tile"=>false,
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/379675477/pose_babi__edited_normal.JPG",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/379675477/pose_babi__edited_normal.JPG",
					    "profile_link_color"=>"990000",
					    "profile_sidebar_border_color"=>"DFDFDF",
					    "profile_sidebar_fill_color"=>"F3F3F3",
					    "profile_text_color"=>"333333",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"febidudung",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Thu May 07 05:53:22 +0000 2015",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[],
					        "user_mentions"=>[]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>596191070200799232,
					      "id_str"=>"596191070200799232",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"en",
					      "place"=>null,
					      "retweet_count"=>0,
					      "retweeted"=>false,
					      "source"=>"
					<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
					      "text"=>"Right company but wrong leader followed by wrong team ... Sigh..... how i missed my agency fellow",
					      "truncated"=>false
					    ],
					    "statuses_count"=>4714,
					    "time_zone"=>"Pacific Time (US & Canada)",
					    "translator_type"=>"none",
					    "url"=>null,
					    "utc_offset"=>-25200,
					    "verified"=>false
					  ],
					  [
					    "contributors_enabled"=>false,
					    "created_at"=>"Thu Oct 06 01:30:11 +0000 2011",
					    "default_profile"=>false,
					    "default_profile_image"=>false,
					    "description"=>"I'm Moeslim",
					    "entities"=>[
					      "description"=>[
					        "urls"=>[]
					      ],
					      "url"=>[
					        "urls"=>[
					          [
					            "display_url"=>"febriamalia89.wordpress.com",
					            "expanded_url"=>"http://www.febriamalia89.wordpress.com",
					            "indices"=>[
					              0,
					              23
					            ],
					            "url"=>"https://t.co/6K8uPcZcWT"
					          ]
					        ]
					      ]
					    ],
					    "favourites_count"=>842,
					    "follow_request_sent"=>false,
					    "followers_count"=>309,
					    "following"=>false,
					    "friends_count"=>236,
					    "geo_enabled"=>true,
					    "has_extended_profile"=>true,
					    "id"=>385735842,
					    "id_str"=>"385735842",
					    "is_translation_enabled"=>false,
					    "is_translator"=>false,
					    "lang"=>"en",
					    "listed_count"=>1,
					    "location"=>"pontianak, Kalimantan Barat",
					    "name"=>"Febi Amalia",
					    "notifications"=>false,
					    "profile_background_color"=>"091D59",
					    "profile_background_image_url"=>"http://pbs.twimg.com/profile_background_images/644830760/bpw5e2xf382zq6e9g9cf.jpeg",
					    "profile_background_image_url_https"=>"https://pbs.twimg.com/profile_background_images/644830760/bpw5e2xf382zq6e9g9cf.jpeg",
					    "profile_background_tile"=>true,
					    "profile_banner_url"=>"https://pbs.twimg.com/profile_banners/385735842/1465175997",
					    "profile_image_url"=>"http://pbs.twimg.com/profile_images/779219689536794624/UMFZrEX8_normal.jpg",
					    "profile_image_url_https"=>"https://pbs.twimg.com/profile_images/779219689536794624/UMFZrEX8_normal.jpg",
					    "profile_link_color"=>"150EE8",
					    "profile_sidebar_border_color"=>"031A09",
					    "profile_sidebar_fill_color"=>"46CC46",
					    "profile_text_color"=>"0E1A0F",
					    "profile_use_background_image"=>true,
					    "protected"=>false,
					    "screen_name"=>"FebiAmalia",
					    "status"=>[
					      "contributors"=>null,
					      "coordinates"=>null,
					      "created_at"=>"Fri Apr 14 04:34:27 +0000 2017",
					      "entities"=>[
					        "hashtags"=>[],
					        "symbols"=>[],
					        "urls"=>[
					          [
					            "display_url"=>"m.youtube.com/watch?v=Zx6kRO\u2026",
					            "expanded_url"=>"https://m.youtube.com/watch?v=Zx6kROD8qbo",
					            "indices"=>[
					              19,
					              42
					            ],
					            "url"=>"https://t.co/1Fq4uDq3Q6"
					          ],
					          [
					            "display_url"=>"instagram.com/p/BS2hnN4FenC/",
					            "expanded_url"=>"https://www.instagram.com/p/BS2hnN4FenC/",
					            "indices"=>[
					              95,
					              118
					            ],
					            "url"=>"https://t.co/csH2GKkqku"
					          ]
					        ],
					        "user_mentions"=>[
					          [
					            "id"=>136885994,
					            "id_str"=>"136885994",
					            "indices"=>[
					              3,
					              15
					            ],
					            "name"=>"Lee Teuk",
					            "screen_name"=>"special1004"
					          ]
					        ]
					      ],
					      "favorite_count"=>0,
					      "favorited"=>false,
					      "geo"=>null,
					      "id"=>852741820819701761,
					      "id_str"=>"852741820819701761",
					      "in_reply_to_screen_name"=>null,
					      "in_reply_to_status_id"=>null,
					      "in_reply_to_status_id_str"=>null,
					      "in_reply_to_user_id"=>null,
					      "in_reply_to_user_id_str"=>null,
					      "is_quote_status"=>false,
					      "lang"=>"ko",
					      "place"=>null,
					      "possibly_sensitive"=>false,
					      "retweet_count"=>3521,
					      "retweeted"=>false,
					      "retweeted_status"=>[
					        "contributors"=>null,
					        "coordinates"=>null,
					        "created_at"=>"Fri Apr 14 04:14:14 +0000 2017",
					        "entities"=>[
					          "hashtags"=>[],
					          "symbols"=>[],
					          "urls"=>[
					            [
					              "display_url"=>"m.youtube.com/watch?v=Zx6kRO\u2026",
					              "expanded_url"=>"https://m.youtube.com/watch?v=Zx6kROD8qbo",
					              "indices"=>[
					                2,
					                25
					              ],
					              "url"=>"https://t.co/1Fq4uDq3Q6"
					            ],
					            [
					              "display_url"=>"instagram.com/p/BS2hnN4FenC/",
					              "expanded_url"=>"https://www.instagram.com/p/BS2hnN4FenC/",
					              "indices"=>[
					                78,
					                101
					              ],
					              "url"=>"https://t.co/csH2GKkqku"
					            ]
					          ],
					          "user_mentions"=>[]
					        ],
					        "favorite_count"=>5890,
					        "favorited"=>false,
					        "geo"=>null,
					        "id"=>852736730402664449,
					        "id_str"=>"852736730402664449",
					        "in_reply_to_screen_name"=>null,
					        "in_reply_to_status_id"=>null,
					        "in_reply_to_status_id_str"=>null,
					        "in_reply_to_user_id"=>null,
					        "in_reply_to_user_id_str"=>null,
					        "is_quote_status"=>false,
					        "lang"=>"ko",
					        "place"=>null,
					        "possibly_sensitive"=>false,
					        "retweet_count"=>3521,
					        "retweeted"=>false,
					        "source"=>"
					<a href=\"http://instagram.com\" rel=\"nofollow\">Instagram</a>",
					        "text"=>"..https://t.co/1Fq4uDq3Q6..\n..YESUNG \uc608\uc131_\ubd04\ub0a0\uc758 \uc18c\ub098\uae30 (Paper Umbrella)_Music Video\u2026 https://t.co/csH2GKkqku",
					        "truncated"=>false
					      ],
					      "source"=>"
					<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
					      "text"=>"RT @special1004=>..https://t.co/1Fq4uDq3Q6..\n..YESUNG \uc608\uc131_\ubd04\ub0a0\uc758 \uc18c\ub098\uae30 (Paper Umbrella)_Music Video\u2026 https://t.co/csH2GKkqku",
					      "truncated"=>false
					    ],
					    "statuses_count"=>17751,
					    "time_zone"=>"Bangkok",
					    "translator_type"=>"none",
					    "url"=>"https://t.co/6K8uPcZcWT",
					    "utc_offset"=>25200,
					    "verified"=>false
					  ]
			);
			header('Content-Type=> application/json');
			echo json_encode($people, JSON_PRETTY_PRINT);
  }



}
